### ISSUE TITLE
fillmissing: movmean and movmedian support

### ISSUE THREAD

**Issue by apjanke** [apjanke/octave-tablicious#37]
Most of `fillmissing()` is implemented, but it's still missing support for the `'movmean'` and `'movmedian'` fill methods.

## References

* https://github.com/apjanke/octave-tablicious/issues/108

**Comment by NRJank** [comment]
@apjanke a version of ismissing, rmmissing, and fillmissing (minus the table portions) have been implemented in the [octave-statistics package](https://github.com/gnu-octave/statistics/tree/main/inst).  (fillmissing did take a while...).  perhaps they can be adapted to work with Tablicious?

**Comment by apjanke** [comment]
Yeah, I bet they could. Or rather, maybe Tablicious could be adapted to work with them.

I think the question is: how should these two libraries interact? The ismissing, rmmissing, and fillmissing functions are top-level or global functions. Only one supplier of these functions can "win" when multiple packages or things that define them are on the Octave path. And I think it would be good if Tablicious would play nicely with octave-statistics.

Since octave-statistics is a much more well-established Octave package than Tablicious, I'm thinking that maybe/probably Tablicious should take octave-statistics as an optional dependency, deferring to it and and saying "the main/generic implementations of the (is/rm/fill)missing functions are provided by octave-statistics; please install that package if you want to use them", and only provide the specialized overrides/extensions of those functions for the particular classes that Tablicious defines (like, `table.fillmissing` or `datetime.rmmissing` methods), with those specialized class-specific implementations possibly depending on the generic function implementations supplied by octave-statistics.

What do you think?

BTW, thanks for the heads-up here; I didn't know that octave-statistics had these.

**Comment by apjanke** [comment]
Closing this in favor of https://github.com/apjanke/octave-tablicious/issues/108, where we'll get Tablicious and Statistics to play nice with each other. Tablicious will defer/delegate to Statistics for all the actual math stuff in `fillmissing()` and the like.

I removed the `fillmissing()` function from Tablicious. It's merged to `main` now, and will be going out in version 0.4.0, hopefully soon.
