### ISSUE TITLE
build: isfile/isfolder shadowing library functions

### ISSUE THREAD

**Issue by arb1961** [apjanke/octave-tablicious#62]
Hi,

I am curious about octave-tablicious, and am trying to build the snapshot.

I get two warnings about isfile/isfolder shadowing of core library functions:

make: Leaving directory `/tmp/oct-6JiB6Y/tablicious-0.4.0-SNAPSHOT/src'
copyfile /tmp/oct-6JiB6Y/tablicious-0.4.0-SNAPSHOT/src/__oct_time_binsearch__.oct /tmp/oct-6JiB6Y/tablicious-0.4.0-SNAPSHOT/inst/x86_64-pc-linux-gnu-api-v53
warning: function /uhome/user/octave-5.1/tablicious-0.4.0-SNAPSHOT/isfile.m shadows a core library function
warning: function /uhome/user/octave-5.1/tablicious-0.4.0-SNAPSHOT/isfolder.m shadows a core library function

**Comment by apjanke** [comment]
Thank you for trying out Tablicious!

That's a bug. Tablicious was written primarily against Octave 4.4.1, and it looks like they've implemented these functions in Octave 5.1.

I'll move them off to a "compatibility shims" folder to avoid the conflict.

**Comment by apjanke** [comment]
Fixed in https://github.com/apjanke/octave-tablicious/commit/079dd81b45d593f55461656243a739ba3a6eb7e8. Could you do a `git pull` and try the new version?

**Comment by apjanke** [comment]
Closing because I think this is fixed now. Please re-open if you're still getting this warning when building the snapshot.

This fix will go out in version 0.3.1, which I will roll out in a couple days.
