### ISSUE TITLE
snapshot build fails in string.m

### ISSUE THREAD

**Issue by arb1961** [apjanke/octave-tablicious#64]
I build in the target directory, launch octave, and then:

pkg install -verbose tablicious-0.4.0-SNAPSHOT.tar.gz

in the end my build fails in this step:

parse error near line 832 of file /uhome/burgersar/octave-5.1/tablicious-0.4.0-SNAPSHOT/string.m

  duplicate subfunction or nested function name

>>>     function out = sprintf (fmt, varargin)
                       ^
error: called from
    doc_cache_create>create_cache at line 109 column 20
    gen_doc_cache_in_dir>@<anonymous> at line 143 column 16
    doc_cache_create>gen_doc_cache_in_dir at line 144 column 9
    doc_cache_create at line 55 column 12
    install>generate_lookfor_cache at line 800 column 5
    install at line 229 column 7
    pkg at line 441 column 9

**Comment by apjanke** [comment]
Dumb duplicated code bug. Fixed in https://github.com/apjanke/octave-tablicious/commit/acf531eae007c7d898ed05679c9db944cadc5d98.

Basic testing would have caught this. Clearly the next thing I need to work on is setting up unit testing and CI for Tablicious.

Thanks for the bug report!
