### ISSUE TITLE
build fail on octave dev: __octave_link_register_doc___ does not exist

### ISSUE THREAD

**Issue by arb1961** [apjanke/octave-tablicious#66]
building on octave dev gives this:

```
error: '__octave_link_register_doc__' undefined near line 36, column 36
error: called from
    load_tablicious at line 36 column 7
```

indeed `__octave_link_register_doc__` has been removed in dev.

This function is an m-file callable C++ wrapper around `octave_link::register_doc`.
`octave_link::register_doc` is still present in dev, but there doesn't seem to be a .m interface any more.

See also [https://savannah.gnu.org/bugs/?55509](url)

**Comment by arb1961** [comment]
see also [https://github.com/apjanke/octave-jsonstuff/issues/2](url)

The function is \_\_octave_link_register_doc\_\_ , no boldface intended ...

**Comment by apjanke** [comment]
Well, crap. Let me talk to the core Octave devs and see what happened to it.

**Comment by apjanke** [comment]
Per @mtmiller:

> The `__octave_link_register_doc__` internal function doesn't exist in Octave 6 any longer, it's now named `__event_manager_register_doc__` since July 2019.

**Comment by mtmiller** [comment]
Yeah, all `__octave_link_xxx__` internal functions are now named `__event_manager_xxx__` on the version 6 branch.

**Comment by apjanke** [comment]
I've checked in a fix on `master`, but I don't have a working dev/default build to test it on. Can one of you try it out?

```
pkg install https://github.com/apjanke/octave-tablicious/archive/master.zip
```

**Comment by mtmiller** [comment]
Yep, works for me!

If you have a system where you can run Linux Docker images, you can use [mtmiller/octave:devel](https://hub.docker.com/r/mtmiller/octave) to follow the development branch.

**Comment by apjanke** [comment]
Oh, cool. I don't know Docker, but now's a good time to learn. Thanks!

Fix released in new version 0.3.2.

Thanks for the bug report, folks!

**Comment by apjanke** [comment]
I fixed jsonstuff, too. Gonna have to go around to all my Octave libraries and do this.

**Comment by mtmiller** [comment]
@apjanke :confused: I installed 0.3.2 from the release link, but after install it calls itself 0.3.1. The tag looks right. Is the release tar.gz different from the tag content?

**Comment by mtmiller** [comment]
Yeah, installing from the [tag link](https://github.com/apjanke/octave-tablicious/archive/v0.3.2.tar.gz) does the right thing, but the [release link](https://github.com/apjanke/octave-tablicious/releases/download/v0.3.2/tablicious-0.3.2.tar.gz) looks like a botched snapshot to me.

**Comment by apjanke** [comment]
D'oh! New release coming up to fix this.

**Comment by apjanke** [comment]
New version 0.3.3 is out. Looks right to me now.

```
octave:3> pkg install https://github.com/apjanke/octave-tablicious/releases/download/v0.3.3/tablicious-0.3.3.tar.gz
[...]
octave:4> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
     control  |   3.2.0 | /Users/janke/octave/control-3.2.0
   jsonstuff  |   0.3.0 | /Users/janke/octave/jsonstuff-0.3.0
  tablicious  |   0.3.3 | /Users/janke/octave/tablicious-0.3.3
octave:5>
```

**Comment by mtmiller** [comment]
LGTM, installs in 4.4, 5.1, and 6.0. Thanks!

**Comment by apjanke** [comment]
Yay!
