### ISSUE TITLE
functions mustBeFinite, et al, shadow a core library function with Octave 6 / devel branch

### ISSUE THREAD

**Issue by mtmiller** [apjanke/octave-tablicious#68]
Install in Octave 6.0 throws shadow warnings about the function files

* mustBeFinite.m
* mustBeInteger.m
* mustBeMember.m
* mustBeNonempty.m
* mustBeNumeric.m
* mustBeReal.m

I guess these functions can be dealt with using the same shim approach as in e9a246102511 and 079dd81b45d5.

**Comment by apjanke** [comment]
Done in https://github.com/apjanke/octave-tablicious/commit/a88b3757f94873bf37afe9c8a91f1b9597e73738.

New release 0.3.4 with this fix is out.

Thank you for the bug reports! These are very useful to me, and it's nice to see people trying out the library.

**Comment by mtmiller** [comment]
Works for me today, thanks!
