### ISSUE TITLE
warning: format ‘%lld’ expects argument of type ‘long long int’ ...

### ISSUE THREAD

**Issue by mtmiller** [apjanke/octave-tablicious#69]
When building / installing with `-Wformat` in CXXFLAGS, this warning message shows up for a single `error` function call with two `%lld` format specifiers in \_\_oct_time_binsearch\_\_.cc.

Depending on how Octave was built and the details of the operating system, `octave_idx_type` may be either a `long int` or a `long long int` type, both are valid.

IMHO the best solution is to inline cast the arguments to `long long int` for the `error` function call. Will submit a PR with that change momentarily.

I've been seeing this for a while, but I forgot to report it until I saw some comments on the mailing list this morning from someone else seeing the same warnings.

**Comment by apjanke** [comment]
> IMHO the best solution is to inline cast the arguments to long long int for the error function call.

Yep, that sounds right, and an easy way to do it.
