### ISSUE TITLE
seconds(1) raises error: no such method or property `ofDays'

### ISSUE THREAD

**Issue by scivision** [apjanke/octave-tablicious#72]
is this an Octave version issue? It seems static method for duration "ofDays" is not picked up, such that with Octave 5.2.0 for:

```matlab
seconds(1)
```
error results

> seconds(1)
error: no such method or property `ofDays'
error: called from
    seconds at line 39 column 9

This happens for tablicious 0.3.5 as well as tip

**Comment by apjanke** [comment]
Hmmmmm. Works for me in Octave 4.4.1 and 5.2.0 on Mac.

```
octave:4> version
ans = 5.2.0
octave:5> addpath /Users/janke/local/repos/octave-tablicious/inst/
octave:6> seconds(3)
ans =
00:00:03

octave:7>
```

```
>> version
ans = 4.4.1
>> addpath /Users/janke/local/repos/octave-tablicious/inst/
>> seconds(3)
ans =
00:00:03
>>
```

Not sure what to tell you here.

**Comment by apjanke** [comment]
Could you do a `dbstop if all error` and rerun this, and show me:
* The complete stack trace from `dbstop`
* The output of `whos`
* The output of `which duration`
* The output of `path`
?

**Comment by scivision** [comment]
I neglected to say, this was on Windows. For other reasons, I rebooted my PC and now this is not an issue. So I'm inclined to say this was a fluke on my system. Sorry for not trying to reboot first.

**Comment by apjanke** [comment]
> Sorry for not trying to reboot first.

Ah, Windows. Yep, I'm inclined to write this off as OS flakeage and not related to the library.

Thanks for the update!

**Comment by scivision** [comment]
yes given that open files can't be overwritten in Windows, and that i was installing and reinstalling and uninstalling various versions of tablicious, probably some files were waiting for a reboot so their state could be flushed
