### ISSUE TITLE
`.Properties` access

### ISSUE THREAD

**Issue by apjanke** [apjanke/octave-tablicious#8]
Matlab's `table` supports the magic `.Properties` dot-reference to access object properties instead of a variable named `Properties`.

This currently doesn't work.

```
>> [s,p,sp] = table_examples.SpDb;
>> s.Properties.VariableNames
error: table has no variable named 'Properties'
error: called from
    getVar at line 575 column 9
    subsref at line 303 column 15
```

Implement this. Needs to be supported for both rvalue (`subsref`) and lvalue (`sugsasgn`) access.

**Comment by apjanke** [comment]
Hmm. I can get `t.Properties` access to work on the RHS using subsref, but it won't work for subsasgn: When I try using it on the LHS, I just get interpreter-level errors, and my `subsasgn` never gets called. Same for {}-indexing.

```
>> [s,p,sp] = table_examples.SpDb;
>> s.Properties.RowNames = 42
error: a cs-list cannot be further indexed
>> s.Properties = 42
error: invalid dot name structure assignment because the structure array is empty.  Specify a subscript on the structure array to resolve.
>> s{2,2} = 'Hello'
error: invalid dot name structure assignment because the structure array is empty.  Specify a subscript on the structure array to resolve.
```

()-indexing works, and calls subsasgn.

Might need to provide alternative access here to work around an Octave limitation. I already have `setvar` for setting full variable values. Will need to provide support for:

* Setting selected values of a variable, selecting variable by name
* Setting selected values of a variable, selecting variable(s) by index
* Setting properties usually accessed with .Properties
  * RowNames
  * VariableNames
  * Description

**Comment by apjanke** [comment]
Added subsref support in https://github.com/apjanke/octave-table/commit/46b79cbe655e61eb749652221838275d722c2c55.

**Comment by apjanke** [comment]
I think I need to report this upstream to Octave.

**Comment by rdzman** [comment]
Just wondering, was this issue resolved by [having `numel` always return 1](https://github.com/apjanke/octave-tablicious/issues/80#issuecomment-855198281)?

**Comment by apjanke** [comment]
> Just wondering, was this issue resolved by having numel always return 1?

I believe it was, and it went out in release 0.3.6. This can probably be closed now. Let me do a little review here.

**Comment by apjanke** [comment]
Yay, it works now! Closing this as Fixed.
