### ISSUE TITLE
table "t.foo = ..." .-indexing assignment is busted

### ISSUE THREAD

**Issue by rdzman** [apjanke/octave-tablicious#80]
Given the following table ...

```
octave:1> T = table([11;22;33], {'uno';'dos';'tres'}, 'VariableNames', {'X','S'});
octave:2> prettyprint(T)
-------------
| X  | S    |
-------------
| 11 | uno  |
| 22 | dos  |
| 33 | tres |
-------------
```

The following assignment operations result in errors (but they all work fine in MATLAB).
```
T.X = [1;2;3];
T.S = {'one'; 'two'; 'three'};
T.S{2} = 'two';
```

The error message in each case is ...
```
error: invalid dot name structure assignment because the structure array is empty.  Specify a subscript on the structure array to resolve.
```

**Comment by apjanke** [comment]
Ah! Yes, I'm afraid this assignment form – assigning to a column/variable using dot-indexing and a name – is totally busted. Sorry for not having an Issue up for it already; it's kiiiinda an important feature.

I have not been able to figure out how to fix this. I suspect it is actually a bug in Octave itself and its handling of `subsasgn` for classdef/MCOS classes. This behavior is supposed to be handled by the `subsasgn` ("SUBScripted ASsiGNment") method. But when I throw this in the Octave debugger, it appears that the `table.subsasgn` method never even gets called.

I need to report this upstream to the core Octave developers but have been kind of busy lately. Thanks for the reminder.

**Comment by apjanke** [comment]
Reported to core Octave at https://savannah.gnu.org/bugs/index.php?60723.

**Comment by apjanke** [comment]
Fernando over on the GNU Octave bug tracker found the problem pretty quickly: the Octave interpreter is calling numel on the subsasgn target, and using that to decide whether it's a valid target for dot-subscripting assignment. <https://savannah.gnu.org/bugs/index.php#comment3>  Tablicious' table.numel is currently returning the actual total number of elements in contained variables, so any nontrivial table returns > 1 for numel(t), and Octave balks at doing a dot-referencing subsasgn.

I couldn't figure out a clever way to have table.numel differentiate these cases using dbstack or whatever.

Calling numel on a table is not really useful, and I've never seen it in the wild. But dot-referenced assignment happens all the time. So we should probably fix this by just having table.numel always return 1.

**Comment by apjanke** [comment]
Okay, in https://github.com/apjanke/octave-tablicious/commit/3a6149fb75274d5b6f73c6f6a0f562a191dca990 I changed `table.numel` to always return 1, and now dot-indexing assignment for tables seems to work:

```text
>> t = table([11;22;33], {'uno';'dos';'tres'}, 'VariableNames', {'X','S'});
>> pp(t)
-------------
| X  | S    |
-------------
| 11 | uno  |
| 22 | dos  |
| 33 | tres |
-------------
>> t.X = [1;2;3];
>> pp(t)
------------
| X | S    |
------------
| 1 | uno  |
| 2 | dos  |
| 3 | tres |
------------
>> t.X(2) = 420.69;
>> pp(t)
-----------------
| X      | S    |
-----------------
| 1      | uno  |
| 420.69 | dos  |
| 3      | tres |
-----------------
>>
```

Can you try it out for your use cases?

I think losing Matlab-compatible numel behavior is well worth getting dot-indexing assignment working.

**Comment by apjanke** [comment]
Calling this fixed, since it seems to work for me. This is going out in release 0.3.6.

**Comment by rdzman** [comment]
Sorry, I forgot to respond here ... but yes, it is working fine for me.

**Comment by apjanke** [comment]
Excellent! Glad we got this sorted.
