### ISSUE TITLE
missing 'DimensionNames' support in constructor

### ISSUE THREAD

**Issue by rdzman** [apjanke/octave-tablicious#88]
The following should set the `DimensionNames` property upon construction as in MATLAB, but it appears it is not supported by the constructor.

```
T = table([1;2;3], 'DimensionNames', {'records', 'fields'});
```

**Comment by apjanke** [comment]
Done in a couple recent commits, including https://github.com/apjanke/octave-tablicious/commit/03f08d5aa1380d202294276dfff7bc1cf5aa9a12 and https://github.com/apjanke/octave-tablicious/commit/8dfa348d5d6a020985d5435a455babbb628d0f46. Will go out in v0.4.0.

```octave
>> T = table([1;2;3], 'DimensionNames', {'records', 'fields'})
T =
table: 3 rows x 1 variables
  VariableNames: Var1
>> T.Properties.DimensionNames
ans =
{
  [1,1] = records
  [1,2] = fields
}

>>
```

Closing as Fixed.
