### ISSUE TITLE
Numeric input for string constructor

### ISSUE THREAD

**Issue by gllmflndn** [apjanke/octave-tablicious#97]
There is an error when the input to the string constructor is a numeric array. The space between `num2str` and `(x)` should be removed in `{num2str (x)}`.

```
>> string (1)
error: Invalid call to num2str.  Correct usage is:

 -- STR = num2str (X)
 -- STR = num2str (X, PRECISION)
 -- STR = num2str (X, FORMAT)
error: called from
    print_usage at line 105 column 5
    num2str at line 84 column 5
    string>@<anonymous> at line 119 column 49
    string at line 119 column 19
```

**Comment by apjanke** [comment]
Nice catch! Looks like it was affecting datetime inputs, too. Fixed in https://github.com/apjanke/octave-tablicious/commit/892f7251d912c0457293e586138e5477c210a422.
